services:
  api:
    build: .
    env_file:
      - .env.local
    environment:
      SQLITE_DB_PATH: /app/data/code_sense.sqlite3
      BASE_REPO_DIR: /app/data
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
